# docker-compose.yml
services:
  sjo-web:
    # ... (konfigurasi sjo-web yang sudah Anda perbaiki)
    user: "1000:1000"
    build:
        context: .
        dockerfile: Dockerfile
    container_name: sjo_web
    volumes:
        - .:/var/www/html
    networks:
        - sjo-web-network

  nginx:
    # ... (konfigurasi nginx yang sudah Anda perbaiki)
    user: "1000:1000"
    build:
        context: .docker/nginx
        dockerfile: Dockerfile
    container_name: nginx_proxy
    volumes:
        - .:/var/www/html
        - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./certs:/etc/letsencrypt # Volume untuk menyimpan sertifikat
    ports:
        - "80:80"   # Port 80 untuk verifikasi Certbot
        - "443:443" # Port 443 untuk HTTPS
    networks:
        - sjo-web-network
    depends_on:
        - sjo-web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx_configs/data:/var/lib/letsencrypt
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sjo-web-network
    command: certonly --webroot --webroot-path=/var/www/html -d yourdomain.com --email your-email@example.com --agree-tos --non-interactive
networks:
  sjo-web-network:
    driver: bridge